### ISSUE TITLE
Investigation: ACCESS-OM2-BGC Versioning

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/ACCESS-OM2-BGC#1]
Some questions that came up on slack regarding the `spack.yaml` of this repository:
* Should the name of the spec be `access-om2` like the existing https://github.com/ACCESS-NRI/access-om2 repo? Could lead to clashes in the `vk83 spack` environment. See https://github.com/ACCESS-NRI/ACCESS-OM2-BGC/blob/af942a80783be7604e60eb523d88a7651c3aa070/spack.yaml#L10-L11. I'm not too sure about remediation actions for this one (@harshula ?) but it might require the creation of a new package in `spack-packages`? Also note that a change to the package name will mean the removal of the `-bgc` bit here: https://github.com/ACCESS-NRI/ACCESS-OM2-BGC/blob/af942a80783be7604e60eb523d88a7651c3aa070/spack.yaml#L59
* Should the versions of `access-om2` and `access-om2-bgc` be in lockstep? Currently, both have the version `@git.2023.11.23`. Would an update to one of the models require an update to the other, or will they drift out of sync? If it's the latter, we should start `access-om2-bgc` at `@git.2024.03.0`. 

And just for my own understanding:
* What is the `type` syntax here? https://github.com/ACCESS-NRI/ACCESS-OM2-BGC/blob/af942a80783be7604e60eb523d88a7651c3aa070/spack.yaml#L16

Tagging @aidanheerdegen as well

**Comment by aidanheerdegen** [comment]
Soz. I've pre-empted this with a forum topic, in case this repo "goes away"/"gets taken"

https://forum.access-hive.org.au/t/access-om2-biogeochemistry-builds-and-deployment/1922

**Comment by CodeGat** [comment]
This has been kinda solved:
* The first point is solved because we are using the new `access-om2-bgc` package here: https://github.com/ACCESS-NRI/spack-packages/pull/81.
* The second point is kinda solved because using a `CalVer`-like format means that updates will probably be mostly in lockstep.
